///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Uibank_Loans_test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("92929bde-8139-4e05-b9fa-a2736296ffa9", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Uibank_Loans_testRepository repository.
        /// </summary>
        public static Uibank_Loans_testRepository repo = Uibank_Loans_testRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
            Msg = "Congrats!";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

        string _Msg;

        /// <summary>
        /// Gets or sets the value of variable Msg.
        /// </summary>
        [TestVariable("77b744e3-236f-403d-97b3-0827111b52f3")]
        public string Msg
        {
            get { return _Msg; }
            set { _Msg = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UiBankGoogleChrome.Element81327008' at Center.", repo.UiBankGoogleChrome.Element81327008Info, new RecordItemIndex(0));
            repo.UiBankGoogleChrome.Element81327008.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UiBankGoogleChrome' at 539;556.", repo.UiBankGoogleChrome.SelfInfo, new RecordItemIndex(1));
            repo.UiBankGoogleChrome.Self.Click("539;556");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UiBankGoogleChrome.Element81327008' at 540;469.", repo.UiBankGoogleChrome.Element81327008Info, new RecordItemIndex(2));
            repo.UiBankGoogleChrome.Element81327008.Click("540;469");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}{NumPad2}{NumPad0}{NumPad0}{NumPad0}' with focus on 'UiBankGoogleChrome'.", repo.UiBankGoogleChrome.SelfInfo, new RecordItemIndex(3));
            repo.UiBankGoogleChrome.Self.PressKeys("{NumPad1}{NumPad2}{NumPad0}{NumPad0}{NumPad0}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UiBankGoogleChrome.Element81327008' at 526;567.", repo.UiBankGoogleChrome.Element81327008Info, new RecordItemIndex(4));
            repo.UiBankGoogleChrome.Element81327008.Click("526;567");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UiBankGoogleChrome' at 547;812.", repo.UiBankGoogleChrome.SelfInfo, new RecordItemIndex(5));
            repo.UiBankGoogleChrome.Self.Click("547;812");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UiBankGoogleChrome.Element81327008' at 539;680.", repo.UiBankGoogleChrome.Element81327008Info, new RecordItemIndex(6));
            repo.UiBankGoogleChrome.Element81327008.Click("539;680");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad3}{NumPad0}{NumPad0}{NumPad0}' with focus on 'UiBankGoogleChrome'.", repo.UiBankGoogleChrome.SelfInfo, new RecordItemIndex(7));
            repo.UiBankGoogleChrome.Self.PressKeys("{NumPad3}{NumPad0}{NumPad0}{NumPad0}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UiBankGoogleChrome.Element81327008' at 515;808.", repo.UiBankGoogleChrome.Element81327008Info, new RecordItemIndex(8));
            repo.UiBankGoogleChrome.Element81327008.Click("515;808");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad3}{NumPad5}' with focus on 'UiBankGoogleChrome'.", repo.UiBankGoogleChrome.SelfInfo, new RecordItemIndex(9));
            repo.UiBankGoogleChrome.Self.PressKeys("{NumPad3}{NumPad5}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -120 units.", new RecordItemIndex(10));
            Mouse.ScrollWheel(-120);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UiBankGoogleChrome.Element81327008' at 736;780.", repo.UiBankGoogleChrome.Element81327008Info, new RecordItemIndex(11));
            repo.UiBankGoogleChrome.Element81327008.Click("736;780");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
