///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Uibank_Loans_test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Uibank_Loans_testRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("b6b76223-db5d-495f-99c1-0163314400c8")]
    public partial class Uibank_Loans_testRepository : RepoGenBaseFolder
    {
        static Uibank_Loans_testRepository instance = new Uibank_Loans_testRepository();
        Uibank_Loans_testRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        Uibank_Loans_testRepositoryFolders.UiBankGoogleChromeAppFolder _uibankgooglechrome;
        Uibank_Loans_testRepositoryFolders.ExplorerAppFolder _explorer;

        /// <summary>
        /// Gets the singleton class instance representing the Uibank_Loans_testRepository element repository.
        /// </summary>
        [RepositoryFolder("b6b76223-db5d-495f-99c1-0163314400c8")]
        public static Uibank_Loans_testRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Uibank_Loans_testRepository() 
            : base("Uibank_Loans_testRepository", "/", null, 0, false, "b6b76223-db5d-495f-99c1-0163314400c8", ".\\RepositoryImages\\Uibank_Loans_testRepositoryb6b76223.rximgres")
        {
            _applicationundertest = new Uibank_Loans_testRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _uibankgooglechrome = new Uibank_Loans_testRepositoryFolders.UiBankGoogleChromeAppFolder(this);
            _explorer = new Uibank_Loans_testRepositoryFolders.ExplorerAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b6b76223-db5d-495f-99c1-0163314400c8")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("cf64fd04-c350-4d08-9726-3c2e6b18ffab")]
        public virtual Uibank_Loans_testRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The UiBankGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("6360adb8-2e3b-44a1-8ebc-1703b2e39880")]
        public virtual Uibank_Loans_testRepositoryFolders.UiBankGoogleChromeAppFolder UiBankGoogleChrome
        {
            get { return _uibankgooglechrome; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("c59b25a5-5e98-4eb6-a533-5e688bda89b2")]
        public virtual Uibank_Loans_testRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Uibank_Loans_testRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("cf64fd04-c350-4d08-9726-3c2e6b18ffab")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _somebodytagInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='uibank.uipath.com']", parentFolder, 30000, null, false, "cf64fd04-c350-4d08-9726-3c2e6b18ffab", "")
            {
                _somebodytagInfo = new RepoItemInfo(this, "SomeBodyTag", "body/?/?/body", "?/?/tag[@tagname='app-root']/body", 30000, null, "91d0be2b-ed07-4cb9-bfef-6e0f959b7497");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cf64fd04-c350-4d08-9726-3c2e6b18ffab")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cf64fd04-c350-4d08-9726-3c2e6b18ffab")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SomeBodyTag item.
            /// </summary>
            [RepositoryItem("91d0be2b-ed07-4cb9-bfef-6e0f959b7497")]
            public virtual Ranorex.BodyTag SomeBodyTag
            {
                get
                {
                    return _somebodytagInfo.CreateAdapter<Ranorex.BodyTag>(true);
                }
            }

            /// <summary>
            /// The SomeBodyTag item info.
            /// </summary>
            [RepositoryItemInfo("91d0be2b-ed07-4cb9-bfef-6e0f959b7497")]
            public virtual RepoItemInfo SomeBodyTagInfo
            {
                get
                {
                    return _somebodytagInfo;
                }
            }
        }

        /// <summary>
        /// The UiBankGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("6360adb8-2e3b-44a1-8ebc-1703b2e39880")]
        public partial class UiBankGoogleChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _element81327008Info;

            /// <summary>
            /// Creates a new UiBankGoogleChrome  folder.
            /// </summary>
            public UiBankGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("UiBankGoogleChrome", "/form[@title='UiBank - Google Chrome']", parentFolder, 30000, null, true, "6360adb8-2e3b-44a1-8ebc-1703b2e39880", "")
            {
                _element81327008Info = new RepoItemInfo(this, "Element81327008", "element[@controlid='81327008']", "element[@controlid='81327008']", 30000, null, "863821a7-356a-405c-95df-82b664e48e60");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6360adb8-2e3b-44a1-8ebc-1703b2e39880")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6360adb8-2e3b-44a1-8ebc-1703b2e39880")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Element81327008 item.
            /// </summary>
            [RepositoryItem("863821a7-356a-405c-95df-82b664e48e60")]
            public virtual Ranorex.Unknown Element81327008
            {
                get
                {
                    return _element81327008Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Element81327008 item info.
            /// </summary>
            [RepositoryItemInfo("863821a7-356a-405c-95df-82b664e48e60")]
            public virtual RepoItemInfo Element81327008Info
            {
                get
                {
                    return _element81327008Info;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("c59b25a5-5e98-4eb6-a533-5e688bda89b2")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            Uibank_Loans_testRepositoryFolders.RunningApplicationsFolder _runningapplications;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "c59b25a5-5e98-4eb6-a533-5e688bda89b2", "")
            {
                _runningapplications = new Uibank_Loans_testRepositoryFolders.RunningApplicationsFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c59b25a5-5e98-4eb6-a533-5e688bda89b2")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c59b25a5-5e98-4eb6-a533-5e688bda89b2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RunningApplications folder.
            /// </summary>
            [RepositoryFolder("0e5e8266-699f-4eab-9991-beff5a01bfd7")]
            public virtual Uibank_Loans_testRepositoryFolders.RunningApplicationsFolder RunningApplications
            {
                get { return _runningapplications; }
            }
        }

        /// <summary>
        /// The RunningApplicationsFolder folder.
        /// </summary>
        [RepositoryFolder("0e5e8266-699f-4eab-9991-beff5a01bfd7")]
        public partial class RunningApplicationsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _ranorexstudio1runningwindowInfo;
            RepoItemInfo _googlechrome1runningwindowInfo;
            RepoItemInfo _outlook2runningwindowsInfo;

            /// <summary>
            /// Creates a new RunningApplications  folder.
            /// </summary>
            public RunningApplicationsFolder(RepoGenBaseFolder parentFolder) :
                    base("RunningApplications", "container[@controlid='40965']//toolbar[@accessiblename='Running applications']", parentFolder, 30000, null, false, "0e5e8266-699f-4eab-9991-beff5a01bfd7", "")
            {
                _ranorexstudio1runningwindowInfo = new RepoItemInfo(this, "RanorexStudio1RunningWindow", "button[16]", "", 30000, null, "e8385d73-b0cc-4831-92cd-496359dea370");
                _googlechrome1runningwindowInfo = new RepoItemInfo(this, "GoogleChrome1RunningWindow", "button[5]", "", 30000, null, "fdd42d47-3983-4150-9cb5-438c420a2e67");
                _outlook2runningwindowsInfo = new RepoItemInfo(this, "Outlook2RunningWindows", "button[6]", "", 30000, null, "cd26aead-74df-414f-8914-29c2b7ed02a2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0e5e8266-699f-4eab-9991-beff5a01bfd7")]
            public virtual Ranorex.ToolBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ToolBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0e5e8266-699f-4eab-9991-beff5a01bfd7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RanorexStudio1RunningWindow item.
            /// </summary>
            [RepositoryItem("e8385d73-b0cc-4831-92cd-496359dea370")]
            public virtual Ranorex.Button RanorexStudio1RunningWindow
            {
                get
                {
                    return _ranorexstudio1runningwindowInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The RanorexStudio1RunningWindow item info.
            /// </summary>
            [RepositoryItemInfo("e8385d73-b0cc-4831-92cd-496359dea370")]
            public virtual RepoItemInfo RanorexStudio1RunningWindowInfo
            {
                get
                {
                    return _ranorexstudio1runningwindowInfo;
                }
            }

            /// <summary>
            /// The GoogleChrome1RunningWindow item.
            /// </summary>
            [RepositoryItem("fdd42d47-3983-4150-9cb5-438c420a2e67")]
            public virtual Ranorex.Button GoogleChrome1RunningWindow
            {
                get
                {
                    return _googlechrome1runningwindowInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The GoogleChrome1RunningWindow item info.
            /// </summary>
            [RepositoryItemInfo("fdd42d47-3983-4150-9cb5-438c420a2e67")]
            public virtual RepoItemInfo GoogleChrome1RunningWindowInfo
            {
                get
                {
                    return _googlechrome1runningwindowInfo;
                }
            }

            /// <summary>
            /// The Outlook2RunningWindows item.
            /// </summary>
            [RepositoryItem("cd26aead-74df-414f-8914-29c2b7ed02a2")]
            public virtual Ranorex.Button Outlook2RunningWindows
            {
                get
                {
                    return _outlook2runningwindowsInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Outlook2RunningWindows item info.
            /// </summary>
            [RepositoryItemInfo("cd26aead-74df-414f-8914-29c2b7ed02a2")]
            public virtual RepoItemInfo Outlook2RunningWindowsInfo
            {
                get
                {
                    return _outlook2runningwindowsInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
